version: '3.8'
services:
  app:
    image: vertretungen_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./app/config.env
    volumes:
      - ./app:/app                                        # Quellcode mounten
      - ./app/data:/app/data
      - ./app/logs:/app/logs
      - ./app/banner_config.json:/app/banner_config.json
    ports:
      - "5000:5000"   # Schüler
      - "5001:5001"   # Lehrer
      - "5003:5003"   # Stundenplan-Rotator
      - "5010:5010"   # Banner
    depends_on:
      - tv-keeper
    restart: unless-stopped
    command: ["/app/start_all.sh"]

  tv-keeper:
    image: tv-keeper:latest
    build:
      context: ./tv-keeper
      dockerfile: Dockerfile
    privileged: true
    devices:
      - /dev/vchiq:/dev/vchiq
    restart: unless-stopped
